export enum MomentLang {
  afrikaans = 'af', // Afrikaans
  arabic_algeria = 'ar-dz', // Arabic (Algeria)
  arabic_kuwait = 'ar-kw', // Arabic (Kuwait)
  arabic_libya = 'ar-ly', // Arabic (Libya)
  arabic_morocco = 'ar-ma', // Arabic (Morocco)
  arabic_saudi_arabia = 'ar-sa', // Arabic (Saudi Arabia)
  arabic_tunisia = 'ar-tn', // Arabic (Tunisia)
  arabic = 'ar', // Arabic
  azerbaijani = 'az', // Azerbaijani
  belarusian = 'be', // Belarusian
  bulgarian = 'bg', // Bulgarian
  bambara = 'bm', // Bambara
  bengali = 'bn', // Bengali
  tibetan = 'bo', // Tibetan
  breton = 'br', // Breton
  bosnian = 'bs', // Bosnian
  catalan = 'ca', // Catalan
  czech = 'cs', // Czech
  chuvash = 'cv', // Chuvash
  welsh = 'cy', // Welsh
  danish = 'da', // Danish
  german_austria = 'de-at', // German (Austria)
  german_switzerland = 'de-ch', // German (Switzerland)
  german = 'de', // German
  divehi = 'dv', // Divehi
  greek = 'el', // Greek
  english_australia = 'en-au', // English (Australia)
  english_canada = 'en-ca', // English (Canada)
  english_united_kingdom = 'en-gb', // English (United Kingdom)
  english_ireland = 'en-ie', // English (Ireland)
  english_new_zealand = 'en-nz', // English (New Zealand)
  english = 'en', // English
  esperanto = 'eo', // Esperanto
  spanish_dominican_republic = 'es-do', // Spanish (Dominican Republic)
  spanish_united_states = 'es-us', // Spanish (United States)
  spanish = 'es', // Spanish
  estonian = 'et', // Estonian
  basque = 'eu', // Basque
  persian = 'fa', // Persian
  finnish = 'fi', // Finnish
  faroese = 'fo', // Faroese
  french_canada = 'fr-ca', // French (Canada)
  french_switzerland = 'fr-ch', // French (Switzerland)
  french = 'fr', // French
  western_frisian = 'fy', // Western Frisian
  scottish_gaelic = 'gd', // Scottish Gaelic
  galician = 'gl', // Galician
  gom_latn = 'gom-latn', // gom (Latin)
  gujarati = 'gu', // Gujarati
  hebrew = 'he', // Hebrew
  hindi = 'hi', // Hindi
  croatian = 'hr', // Croatian
  hungarian = 'hu', // Hungarian
  armenian_armenia = 'hy-am', // Armenian (Armenia)
  indonesian = 'id', // Indonesian
  icelandic = 'is', // Icelandic
  italian = 'it', // Italian
  japanese = 'ja', // Japanese
  javanese = 'jv', // Javanese
  georgian = 'ka', // Georgian
  kazakh = 'kk', // Kazakh
  khmer = 'km', // Khmer
  kannada = 'kn', // Kannada
  korean = 'ko', // Korean
  kirghiz = 'ky', // Kirghiz
  luxembourgish = 'lb', // Luxembourgish
  lao = 'lo', // Lao
  lithuanian = 'lt', // Lithuanian
  latvian = 'lv', // Latvian
  me = 'me', // me
  maori = 'mi', // Maori
  macedonian = 'mk', // Macedonian
  malayalam = 'ml', // Malayalam
  marathi = 'mr', // Marathi
  malay_malaysia = 'ms-my', // Malay (Malaysia)
  malay = 'ms', // Malay
  maltese = 'mt', // Maltese
  burmese = 'my', // Burmese
  norwegian_bokmal = 'nb', // Norwegian Bokmål
  nepali = 'ne', // Nepali
  dutch_belgium = 'nl-be', // Dutch (Belgium)
  dutch = 'nl', // Dutch
  norwegian_nynorsk = 'nn', // Norwegian Nynorsk
  punjabi_india = 'pa-in', // Punjabi (India)
  polish = 'pl', // Polish
  portuguese_brazil = 'pt-br', // Portuguese (Brazil)
  portuguese = 'pt', // Portuguese
  romanian = 'ro', // Romanian
  russian = 'ru', // Russian
  sindhi = 'sd', // Sindhi
  sami = 'se', // Northern Sami
  sinhala = 'si', // Sinhala
  slovak = 'sk', // Slovak
  slovenian = 'sl', // Slovenian
  albanian = 'sq', // Albanian
  serbian_cyrillic = 'sr-cyrl', // Serbian (Cyrillic)
  serbian = 'sr', // Serbian
  swati = 'ss', // Swati
  swedish = 'sv', // Swedish
  swahili = 'sw', // Swahili
  tamil = 'ta', // Tamil
  telugu = 'te', // Telugu
  tetum = 'tet', // Tetum
  thai = 'th', // Thai
  tagalog_philippines = 'tl-ph', // Tagalog (Philippines)
  klingon = 'tlh', // Klingon
  turkish = 'tr', // Turkish
  tzl = 'tzl', // tzl
  tzm_latin = 'tzm-latn', // tzm (Latin)
  tzm = 'tzm', // tzm
  ukrainian = 'uk', // Ukrainian
  urdu = 'ur', // Urdu
  uzbek_latin = 'uz-latn', // Uzbek (Latin)
  uzbek = 'uz', // Uzbek
  vietnamese = 'vi', // Vietnamese
  x_pseudo = 'x-pseudo', // x-pseudo
  yoruba = 'yo', // Yoruba
  chinese_china = 'zh-cn', // Chinese (China)
  chinese_hong_kong = 'zh-hk', // Chinese (Hong Kong SAR China)
  chinese_taiwan = 'zh-tw', // Chinese (Taiwan)
}
